version: '3'

services:

  github-release:
    image: 'github-release'
    build: './src'

  www:
    image: 'tmvdl/projects:hidden'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  api:
    image: 'tmvdl/projects:hidden-api'
    build: './src/api'
    environment:
      - 'DATA_PATH=/data'
      - 'PORT=80'
    volumes:
      - './src/api:/app'
      - './data:/data'
    ports:
      - '8080:80'
